version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: go-api
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://admin:senha123@mongodb:27017
      DB_NAME: meu_banco

volumes:
  mongo_data: